import Foundation
import SwiftData

/// A ReadingUnit is a ~5-10 minute reading segment.
/// This is the atomic unit of Spine's daily reading engine.
///
/// Units are generated by the SegmentationEngine from chapters.
/// Each unit has stable character offsets back to the source chapter
/// to support highlight anchoring and future AI retrieval.
@Model
final class ReadingUnit {
    @Attribute(.unique) var id: UUID
    var book: Book?
    var chapter: Chapter?
    
    /// Global ordinal across the entire book (0-indexed).
    var ordinal: Int
    
    /// Display title for the unit, e.g. "Chapter 3 — Part 2".
    var title: String
    
    /// Plain-text content for this unit.
    @Attribute(.externalStorage) var plainText: String
    
    /// Normalized HTML content for rendering.
    @Attribute(.externalStorage) var htmlContent: String
    
    /// Word count for this specific unit.
    var wordCount: Int
    
    /// Estimated reading time in minutes (based on configurable WPM).
    var estimatedMinutes: Double
    
    /// Character offset into the chapter's plainText where this unit starts.
    var startCharOffset: Int
    
    /// Character offset into the chapter's plainText where this unit ends.
    var endCharOffset: Int
    
    var createdAt: Date
    
    /// Whether this unit has been completed by the reader.
    var isCompleted: Bool
    
    /// When this unit was completed.
    var completedAt: Date?
    
    /// User's private notes/micro-review for this unit.
    var privateNotes: String?
    
    // MARK: - Relationships
    
    @Relationship(deleteRule: .cascade, inverse: \Highlight.readingUnit)
    var highlights: [Highlight] = []
    
    @Relationship(deleteRule: .cascade, inverse: \Reaction.readingUnit)
    var reactions: [Reaction] = []
    
    init(
        book: Book? = nil,
        chapter: Chapter? = nil,
        ordinal: Int,
        title: String,
        plainText: String,
        htmlContent: String,
        wordCount: Int,
        estimatedMinutes: Double,
        startCharOffset: Int = 0,
        endCharOffset: Int = 0
    ) {
        self.id = UUID()
        self.book = book
        self.chapter = chapter
        self.ordinal = ordinal
        self.title = title
        self.plainText = plainText
        self.htmlContent = htmlContent
        self.wordCount = wordCount
        self.estimatedMinutes = estimatedMinutes
        self.startCharOffset = startCharOffset
        self.endCharOffset = endCharOffset
        self.isCompleted = false
        self.createdAt = Date()
    }
}
